version: '3'

services:
  crypto-mysql:
    container_name: crypto-mysql
    image: mysql:8
    build:
      context: ..
      dockerfile: mysql-dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
      'mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci',
      '--default-authentication-plugin=mysql_native_password'
    ]
    environment:
      MYSQL_DATABASE: 'crypto'
      MYSQL_ROOT_PASSWORD: crypto2025!
      TZ: Asia/Shanghai

  crypto-server:
    container_name: crypto-server
    build:
      context: .
      dockerfile: crypto-dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./crypto/logs:/home/crypto/logs
      - ./crypto/uploadPath:/home/crypto/uploadPath
    depends_on:
      - crypto-mysql
    links:
      - crypto-mysql